### PR TITLE
Server persistence

### LINKED ISSUE #157: Server persistence
Add a persistence layer to `radicle-server` so data isn't all lost on crashes/restarts.

*Not* part of this task is a migration story for `radicle` updates that affect syntax or semantics.

### PR DESCRIPTION
**Pull request by jkarni**
Fixes #157.

### CODE REVIEW

File: exe/Server/Server.hs [hunk 1]
```diff
@@ -1,101 +1,203 @@
...
+    createIfNotExists conn
+    res <- getAllDB conn
+    chainPairs <- forM res $ \(name, vals) -> do
+        let st = runIdentity $ runLang pureEnv $ foldM_ (\_ x -> void $ eval x) () vals
+        case st of
+            (Left err, _) -> panic $ show err
+            (Right _, st') -> do
+                let c = Chain { chainName = name
+                              , chainState = st'
+                              , chainEvalPairs = mempty
```
Comment (jkarni) [inline exe/Server/Server.hs]: Hm, screwed up here. Need to keep the value pairs too
